# Generated by Django 3.0.2 on 2020-01-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='sports',
            field=models.ManyToManyField(help_text='Seleccione uno o más deportes en los que compite.', to='tokio2020.Sport'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='libras', max_digits=5, max_length=50, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='event',
            name='result',
            field=models.CharField(max_length=50, null=True, verbose_name='Resultado'),
        ),
    ]
