# Generated by Django 3.0.2 on 2020-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('image', models.ImageField(upload_to='', verbose_name='Foto')),
                ('birthday', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('birthplace', models.CharField(max_length=50, verbose_name='Lugar de nacimiento')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('weight', models.DecimalField(decimal_places=2, help_text='libras', max_digits=5, max_length=50, verbose_name='Nombres')),
                ('height', models.DecimalField(decimal_places=2, help_text='metros', max_digits=3, max_length=50, verbose_name='Altura')),
                ('coach', models.CharField(max_length=100, verbose_name='Entrenador')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellidos'),
        ),
    ]
