# Generated by Django 3.0.3 on 2020-02-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0006_auto_20200131_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/athletes', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='icono',
            field=models.FileField(blank=True, null=True, upload_to='assets/icons', verbose_name='Ícono'),
        ),
    ]
