# Generated by Django 3.0.3 on 2020-02-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0007_auto_20200204_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url_video',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Video del evento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='result',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resultado'),
        ),
    ]
