# Generated by Django 3.0.3 on 2020-02-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0008_auto_20200205_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='mode_id',
            new_name='mode',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='sport_id',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='mode',
            old_name='sport_id',
            new_name='sport',
        ),
    ]
