# Generated by Django 3.0.3 on 2020-02-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokio2020', '0009_auto_20200206_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='modes',
            field=models.ManyToManyField(help_text='Seleccione uno o más modos en los que compite.', to='tokio2020.Mode'),
        ),
    ]
